import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import SessionValidator from "@/components/SessionValidator";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={`${raleway.variable} antialiased px-4 sm:px-6 md:px-10 lg:px-16 sm:py-5 py-3`}>
        <SessionValidator />
        {children}
      </body>
    </html>
  );
}
